### PR TITLE
change groupId back to launchconfig

### PR DESCRIPTION
**Pull request by jmcampanini**

### CODE REVIEW

**Comment by jmcampanini** [comment]
// + @qinfchen feel free to merge if you agree

**Comment by qinfchen** [comment]
so the usage would be `apply plugin: com.palantir.launchconfig.launch-config`? that seems more verbose than needed. would it make sense to follow baseline's convention? using com palantir as the group id

**Comment by qinfchen** [comment]
@jmcampanini ?

**Comment by zoubeiri** [comment]
👍

**Pull request merged**
